Add functionality to create labels for repos in an organisation
isisbusapps/org-label-manager pull request #2
Opened 2018-01-30 11:01 UTC by TickleThePanda

2018-01-30 12:04 UTC, shodder requested changes

2018-01-30 12:04 UTC, shodder commented on index.js
> +let request = require('request-promise-native');
as these are never re-assigned, they could be `const` rather than `let`

2018-01-31 09:27 UTC, shodder approved these changes

2018-01-31 09:45 UTC, srconway approved these changes

2018-02-01 09:06 UTC, merged